# Generated by Django 5.2.7 on 2025-11-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employeeId', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='employee_profile_pics/')),
                ('app_icon', models.ImageField(blank=True, max_length=255, null=True, upload_to='app_icons/')),
                ('employee_type', models.CharField(choices=[('service', 'Service'), ('deliver', 'Deliver'), ('office', 'Office'), ('mechanic', 'Mechanic')], default='service', max_length=20)),
                ('designation', models.CharField(choices=[('car_service_associate', 'Car Service Associate'), ('service_advisor', 'Service Advisor'), ('service_supervisor', 'Service Supervisor'), ('service_manager', 'Service Manager')], default='car_service_associate', max_length=30)),
                ('department', models.CharField(choices=[('service', 'Service Department'), ('delivery', 'Delivery Department'), ('office', 'Office Administration'), ('mechanic', 'Mechanic Department'), ('quality', 'Quality Control'), ('customer_service', 'Customer Service'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('it', 'IT Support')], default='service', max_length=30)),
                ('branch_location', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, default='Your Company Name', max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('child', 'Child'), ('friend', 'Friend'), ('other', 'Other')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
