# Generated by Django 5.2.7 on 2025-12-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
