# Generated by Django 5.2.7 on 2025-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
