# Generated by Django 5.2.7 on 2025-11-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.CharField(choices=[('field_service_specialist', 'Field Service Specialist')], default='field_service_specialist', max_length=30),
        ),
    ]
