# Generated by Django 5.2.7 on 2025-12-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_employee_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
