# Generated by Django 5.2.7 on 2025-12-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_employee_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
