# Generated by Django 5.2.7 on 2025-12-05 06:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Announcement',
                'verbose_name_plural': 'Company Announcements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], max_length=10)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('check_time', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_break_time', models.DurationField()),
                ('number_of_scheduled_breaks', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreakTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch Break'), ('coffee', 'Coffee Break'), ('stretch', 'Stretch Break'), ('other', 'Other')], max_length=20)),
                ('custom_break_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(default='10 min', max_length=20)),
                ('break_start_time', models.CharField(max_length=50)),
                ('break_end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('end_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_timers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20, verbose_name='Category of Leave')),
                ('start_date', models.DateField(verbose_name='From')),
                ('end_date', models.DateField(verbose_name='To')),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Total Number of Leave Days')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for the Leave')),
                ('passport_required_from', models.DateField(blank=True, null=True, verbose_name='Passport Required From')),
                ('passport_required_to', models.DateField(blank=True, null=True, verbose_name='Passport Required to')),
                ('address_during_leave', models.TextField(blank=True, null=True, verbose_name='Address During the Leave')),
                ('ticket_eligibility', models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('partial', 'Partial')], max_length=20, null=True, verbose_name='Ticket Eligibility')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='Attach Media')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
