# Generated by Django 5.2.7 on 2025-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecheck',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='breaktimer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='breaktimer',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='passport_required_from',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='passport_required_to',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='breaktimer',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='ticket_eligibility',
            field=models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('partial', 'Partial')], max_length=100, null=True, verbose_name='Ticket Eligibility'),
        ),
    ]
