# Generated by Django 5.2.7 on 2025-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecheck',
            name='time_zone',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancecheck',
            name='check_time',
            field=models.CharField(max_length=100),
        ),
    ]
