# Generated by Django 5.2.7 on 2025-12-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_attendancecheck_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecheck',
            name='check_date',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
