# Generated by Django 5.2.7 on 2025-11-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_attendancecheck_time_zone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancecheck',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
