# Generated by Django 5.2.7 on 2025-11-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_breaktimer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktimer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
