# Generated by Django 5.2.7 on 2025-11-18 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_attendancecheck_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyannouncement',
            options={'ordering': ['-date'], 'verbose_name': 'Company Announcement', 'verbose_name_plural': 'Company Announcements'},
        ),
        migrations.RenameField(
            model_name='companyannouncement',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='companyannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
