# Generated by Django 5.2.7 on 2025-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_attendancecheck_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktimer',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
