# Generated by Django 5.2.7 on 2025-11-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_companyannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktimer',
            name='custom_break_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breaktimer',
            name='end_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breaktimer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaktimer',
            name='break_end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='breaktimer',
            name='break_start_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='breaktimer',
            name='break_type',
            field=models.CharField(choices=[('lunch', 'Lunch Break'), ('coffee', 'Coffee Break'), ('stretch', 'Stretch Break'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breaktimer',
            name='duration',
            field=models.CharField(default='10 min', max_length=20),
        ),
    ]
