# Generated by Django 5.2.7 on 2025-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_breaktimer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='passport_required_from',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='passport_required_to',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signature_attachments/', verbose_name='Attach Media'),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
