# Generated by Django 5.2.7 on 2025-12-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_leave_end_date_leave_passport_required_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='passport_required_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='passport_required_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
