# Generated by Django 5.2.7 on 2025-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='passport_required_to',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Required to'),
        ),
    ]
