# Generated by Django 5.2.7 on 2025-11-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_number', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('emirates_id_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('visa_copy', 'Visa Photo Copy'), ('labour_card', 'Labour Card Copy'), ('passport_copy', 'Passport Copy'), ('emirates_id', 'Emirates ID Copy'), ('work_permit', 'Work Permit Copy')], max_length=20)),
                ('document_file', models.FileField(max_length=255, upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visa_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profileapp.visadetails')),
            ],
        ),
    ]
