# Generated by Django 5.2.7 on 2025-12-18 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=60, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], max_length=20)),
                ('insurance_expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryVehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='temporary_vehicles_history/')),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('assigned_time', models.TimeField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('ending_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Auto-Expired')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_vehicle_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Temporary Vehicle Histories',
                'ordering': ['-ending_date', '-ending_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_vehicle_assigned_date', models.DateField(blank=True, null=True)),
                ('current_vehicle_assigned_time', models.TimeField(blank=True, null=True)),
                ('current_vehicle_ending_date', models.DateField(blank=True, null=True)),
                ('current_vehicle_ending_time', models.TimeField(blank=True, null=True)),
                ('temporary_vehicle_image', models.ImageField(blank=True, help_text='Image of the temporary vehicle', null=True, upload_to='temporary_vehicles/')),
                ('temporary_vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('temporary_vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('temporary_vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('temporary_vehicle_fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('temporary_vehicle_insurance_expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('temporary_vehicle_assigned_date', models.CharField(blank=True, max_length=100, null=True)),
                ('temporary_vehicle_assigned_time', models.CharField(blank=True, max_length=100, null=True)),
                ('temporary_vehicle_ending_date', models.CharField(blank=True, max_length=100, null=True)),
                ('temporary_vehicle_ending_time', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes for temporary vehicle assignment', null=True)),
                ('location', models.CharField(blank=True, help_text='Location where temporary vehicle is assigned', max_length=255, null=True)),
                ('status', models.CharField(choices=[('current_vehicle', 'Current Vehicle'), ('temporary_vehicle', 'Temporary Vehicle')], default='current_vehicle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignment', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='profileapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('vehicle_issue_image', models.ImageField(blank=True, null=True, upload_to='vehicle_issue/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_vehicle_issues', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='profileapp.vehicle')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='VisaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('emirates_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('emirates_id_expiry', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('visa_copy', 'Visa Photo Copy'), ('labour_card', 'Labour Card Copy'), ('passport_copy', 'Passport Copy'), ('emirates_id', 'Emirates ID Copy'), ('work_permit', 'Work Permit Copy')], max_length=20)),
                ('document_file', models.FileField(max_length=255, upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visa_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profileapp.visadetails')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOdometerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('start_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='profileapp.vehicle')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('vehicle', 'reading_date')},
            },
        ),
    ]
