# Generated by Django 5.2.7 on 2025-12-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visadetails',
            name='visa_number',
        ),
    ]
