# Generated by Django 5.2.7 on 2025-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visadetails',
            name='emirates_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
