# Generated by Django 5.2.7 on 2025-11-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_visadetails_emirates_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visadetails',
            old_name='emirates_id',
            new_name='emirates_id_number',
        ),
    ]
