# Generated by Django 5.2.7 on 2025-12-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_vehicle_vehicleassignment_vehicleissue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleissue',
            name='description',
        ),
    ]
