# Generated by Django 5.2.7 on 2025-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_remove_vehicleissue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleissue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleissue',
            name='vehicle_issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_issue/'),
        ),
    ]
