# Generated by Django 5.2.7 on 2025-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_vehicleissue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='location',
            field=models.CharField(blank=True, help_text='Location where temporary vehicle is assigned', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes for temporary vehicle assignment', null=True),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_assigned_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_ending_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_assigned_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_ending_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
