# Generated by Django 5.2.7 on 2025-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_alter_vehicle_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleassignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicleassignment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='vehicleassignment',
            name='temporary_vehicle',
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='current_vehicle_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='current_vehicle_assigned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='current_vehicle_ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='status',
            field=models.CharField(choices=[('current_vehicle', 'Current Vehicle'), ('temporary_vehicle', 'Temporary Vehicle')], default='current_vehicle', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_fuel_type',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_insurance_expiry_date',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_model',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_number',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_type',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
