# Generated by Django 5.2.7 on 2025-12-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_vehicleassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='current_vehicle_ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
