# Generated by Django 5.2.7 on 2025-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_vehicleassignment_current_vehicle_ending_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_insurance_expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='temporary_vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
