# Generated by Django 5.2.7 on 2025-12-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_alter_vehicleassignment_temporary_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='temporary_vehicle_image',
            field=models.ImageField(blank=True, help_text='Image of the temporary vehicle', null=True, upload_to='temporary_vehicles/'),
        ),
    ]
