# Generated by Django 5.2.7 on 2025-12-08 09:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('nothing', 'Nothing Task'), ('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service/Detailing')], max_length=20)),
                ('heading', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('paused', 'Paused'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('task_assign_time', models.DateTimeField(blank=True, null=True)),
                ('task_start_time', models.DateTimeField(blank=True, null=True)),
                ('task_completed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('vehicle_details', models.TextField(blank=True, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_image_before', models.ImageField(blank=True, null=True, upload_to='vehicle_images/before/')),
                ('vehicle_image_after', models.ImageField(blank=True, null=True, upload_to='vehicle_images/after/')),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_notes', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_type', models.CharField(choices=[('nothing', 'Nothing'), ('ongoing', 'Ongoing'), ('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service'), ('mechanic', 'Mechanic')], default='nothing', max_length=20)),
                ('percentage_completed', models.IntegerField(default=0)),
                ('is_nothing_task', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTaskDax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailing_site', models.CharField(choices=[('mq_dubai_showroom', 'MQ Dubai Showroom (SZR)'), ('mq_delta_service', 'MQ Delta Service Center'), ('mq_ai_quad_service', 'MQ AI Quad Service Center'), ('mq_shirajah_showroom', 'MQ Shirajah Showroom'), ('mq_abu_dhabi_showroom', 'MQ Abu Dhabi Showroom'), ('mq_abu_dhabi_service', 'MQ Abu Dhabi Service Center'), ('mq_ai_ain_showroom', 'MQ AI Ain Showroom'), ('mq_ai_ain_service', 'MQ AI Ain Service Center'), ('mq_fujianni_showroom', 'MQ Fujianni Showroom'), ('mq_fujianni_service', 'MQ Fujianni Service Center'), ('premier_car_care', 'Premier Car Care (Ellie Motors)'), ('camps_ai_quad', 'Camps (AI Quad)'), ('emperor_garage', 'Emperor Garage'), ('five_star_garage', 'Five Star Garage'), ('golden_palace', 'Golden Palace'), ('pos_automotive', 'POS Automotive'), ('office', 'Office'), ('others', 'Others')], max_length=50)),
                ('other_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('exterior_detailing', 'Exterior Detailing'), ('interior_detailing', 'Interior Detailing'), ('interior_exterior_detailing', 'Interior & Exterior Detailing'), ('tinting', 'Tinting'), ('ceramic_coating', 'Ceramic Coating'), ('borophene_coating', 'Borophene Coating'), ('graphene_coating', 'Graphene Coating'), ('ppf', 'PPF'), ('others', 'Others')], max_length=50)),
                ('tinting_type', models.CharField(blank=True, choices=[('standard', 'Standard Tinting'), ('premium', 'Premium Tinting'), ('roll', 'Roll'), ('meter', 'Meter')], max_length=20, null=True)),
                ('tinting_percentage', models.CharField(blank=True, choices=[('0', '0%'), ('30', '30%'), ('50', '50%'), ('70', '70%')], max_length=3, null=True)),
                ('tinting_custom_text', models.CharField(blank=True, max_length=255, null=True)),
                ('coating_layers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1_layer', '1 Layer'), ('2_layer', '2 Layer'), ('3_layer', '3 Layer')], max_length=10), blank=True, default=list, null=True, size=None)),
                ('ppf_type', models.CharField(blank=True, choices=[('ppf_prudence', 'PPF PRUDENCE'), ('ppf_st_quard', 'PPF ST. QUARD'), ('ppf_matte', 'PPF MATTE'), ('ppf_magnifence', 'PPF MAGNIFENCE'), ('ppf_dazzling_silver', 'PPF DAZZLING SILVER'), ('roll', 'Roll'), ('meter', 'Meter')], max_length=30, null=True)),
                ('ppf_custom_text', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional materials used or other notes', null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make_model', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_status', models.CharField(blank=True, choices=[('invoice_received', 'Invoice Received'), ('pri_received', 'PRI Received'), ('yes', 'Yes'), ('no', 'No')], max_length=20, null=True)),
                ('invoice_pri_image', models.ImageField(blank=True, null=True, upload_to='invoice_pri_images/')),
                ('work_location', models.CharField(max_length=255)),
                ('shared_staff_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dax_tasks', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('car_wash', 'Car Wash'), ('full_service', 'Full Service'), ('paint_protection_film_wrapping', 'Paint Protection - Film Wrapping'), ('window_tinting', 'Window - Tinting'), ('advanced_borophene_coating', 'Advanced Borophene - Coating'), ('premium_graphene_coating', 'Premium Graphene - Coating'), ('premium_nanoceramic_coating', 'Premium Nanoceramic - Coating'), ('exterior_detailing', 'Exterior - Detailing'), ('interior_detailing', 'Interior - Detailing')], max_length=50)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('vin_number', models.CharField(max_length=100)),
                ('vin_image', models.ImageField(blank=True, null=True, upload_to='vin_images/')),
                ('shared_staff_details', models.TextField(blank=True, null=True)),
                ('work_location', models.CharField(max_length=255)),
                ('work_start_time', models.DateTimeField(blank=True, null=True)),
                ('work_end_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_task_type', models.CharField(choices=[('employee_verification', 'Employee Verification'), ('task_verification', 'Task Verification'), ('record_work', 'Record Daily Work'), ('send_reminders', 'Send Reminders'), ('view_profiles', 'View Employee Profiles')], max_length=50)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('employee_profiles_to_review', models.TextField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_details', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_numbers', models.TextField()),
                ('delivery_location', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.duty')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_duties', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_progress_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_images', to='task.task')),
            ],
        ),
    ]
