# Generated by Django 5.2.7 on 2025-11-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('nothing', 'Nothing Task'), ('ongoing', 'Ongoing Task'), ('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service/Detailing'), ('mechanic', 'Mechanic')], max_length=20)),
                ('heading', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('paused', 'Paused'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('task_time', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_notes', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_type', models.CharField(choices=[('nothing', 'Nothing'), ('ongoing', 'Ongoing'), ('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service'), ('mechanic', 'Mechanic')], default='nothing', max_length=20)),
                ('percentage_completed', models.IntegerField(default=0)),
                ('is_nothing_task', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('detailing_interior', 'Detailing - Interior'), ('detailing_exterior', 'Detailing - Exterior'), ('car_wash', 'Car Wash'), ('full_service', 'Full Service'), ('interior_cleaning', 'Interior Cleaning'), ('exterior_cleaning', 'Exterior Cleaning')], max_length=50)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('vehicle_details', models.TextField()),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vin_number', models.CharField(max_length=100)),
                ('vin_image', models.ImageField(blank=True, null=True, upload_to='vin_images/')),
                ('vehicle_image_before', models.ImageField(blank=True, null=True, upload_to='vehicle_images/before/')),
                ('vehicle_image_after', models.ImageField(blank=True, null=True, upload_to='vehicle_images/after/')),
                ('shared_staff_details', models.TextField(blank=True, null=True)),
                ('work_location', models.CharField(max_length=255)),
                ('work_start_time', models.DateTimeField()),
                ('work_end_time', models.DateTimeField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_task_type', models.CharField(choices=[('employee_verification', 'Employee Verification'), ('task_verification', 'Task Verification'), ('record_work', 'Record Daily Work'), ('send_reminders', 'Send Reminders'), ('view_profiles', 'View Employee Profiles')], max_length=50)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('employee_profiles_to_review', models.TextField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_details', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_numbers', models.TextField()),
                ('delivery_location', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='task.task')),
            ],
        ),
    ]
