# Generated by Django 5.2.7 on 2025-12-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='vehicle_make_model',
        ),
    ]
