# Generated by Django 5.2.7 on 2025-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='work_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='work_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
