# Generated by Django 5.2.7 on 2025-11-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_servicetask_work_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks', to='task.task'),
        ),
    ]
