# Generated by Django 5.2.7 on 2025-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_servicetask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetask',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='vehicle_image_after',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='vehicle_image_before',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle_image_after',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/after/'),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle_image_before',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/before/'),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
