# Generated by Django 5.2.7 on 2025-11-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_servicetask_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='service_type',
            field=models.CharField(choices=[('car_wash', 'Car Wash'), ('full_service', 'Full Service'), ('paint_protection_film_wrapping', 'Paint Protection - Film Wrapping'), ('window_tinting', 'Window - Tinting'), ('advanced_borophene_coating', 'Advanced Borophene - Coating'), ('premium_graphene_coating', 'Premium Graphene - Coating'), ('premium_nanoceramic_coating', 'Premium Nanoceramic - Coating'), ('exterior_detailing', 'Exterior - Detailing'), ('interior_detailing', 'Interior - Detailing')], max_length=50),
        ),
    ]
