# Generated by Django 5.2.7 on 2025-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_servicetask_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_time',
            new_name='task_assign_time',
        ),
        migrations.AddField(
            model_name='task',
            name='task_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('nothing', 'Nothing Task'), ('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service/Detailing')], max_length=20),
        ),
    ]
