# Generated by Django 5.2.7 on 2025-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_task_time_task_task_assign_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
